channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.7.9
- pip:
  - mlflow
  - azureml-train-automl-runtime==1.44.0
  - inference-schema
  - azureml-interpret==1.44.0
  - azureml-defaults==1.44.0
  - pytorch-transformers==1.0.0
  - spacy==2.1.8
  - https://aka.ms/automl-resources/packages/en_core_web_sm-2.1.0.tar.gz
- numpy==1.18.5
- pandas==1.1.5
- scikit-learn==0.22.1
- py-xgboost==1.3.3
- fbprophet==0.7.1
- holidays==0.10.3
- psutil==5.8.0
- pytorch==1.4.0
- cudatoolkit==9.0
name: project_environment
